spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  web:
    resources:
      static-locations: ${SPRING_WEB_RESOURCES_STATIC_LOCATIONS}

kafka:
  topic:
    name: ${KAFKA_TOPIC_NAME}
    partitions: ${KAFKA_TOPIC_PARTITIONS}
    replicas: ${KAFKA_TOPIC_REPLICAS}
    retention-ms: ${KAFKA_TOPIC_RETENTION_MS}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

springdoc:
  swagger-ui:
    url: ${SPRINGDOC_SWAGGER_UI_URL}
